import {
  GiMetalBar,
  GiHatchet,
  GiWoodStick,
  GiKite,
  GiWoodPile,
  GiCrosscutSaw,
  GiWoodBeam,
  GiSpellBook,
  GiMountainCave,
  GiWoodCabin,
  GiGlassShot,
  GiFamilyHouse,
  GiMagnifyingGlass,
  GiMicroscope,
  GiFactory,
  GiIBeam,
  GiClothes,
  GiChemicalDrop,
  GiLightningArc,
  GiPlug,
  GiMedicines,
  GiSteamLocomotive,
  GiLightBulb,
  GiCaveman,
  GiFarmer,
  GiMineExplosion,
  GiCartwheel,
  GiRaceCar,
  GiMadScientist,
  GiMushroomCloud,
  GiMaterialsScience,
  GiAngelOutfit,
  GiCampfire,
  GiGroundSprout,
  GiStripedSun,
  GiSteam,
  GiWaterDrop,
  GiIceCube,
  GiHeavyRain,
  GiTornado,
  GiSnowing,
  GiWheat,
} from "react-icons/gi";
import { MdOutlineFamilyRestroom } from "react-icons/md";
import { FcLibrary } from "react-icons/fc";
import { IoThunderstormSharp } from "react-icons/io5";
import { HiFire } from "react-icons/hi";
import { WiWindy } from "react-icons/wi";
import { BsWind, BsFileText, BsBuilding, BsTools } from "react-icons/bs";
import { FaMountain, FaSchool, FaTree, FaBacteria } from "react-icons/fa";
import { IconType } from "react-icons";

export interface ingredient {
  name: string;
  isActive: boolean;
  icon?: IconType;
  color: string;
  mix?: string;
}

export const ingredientsArr: ingredient[] = [
  {
    name: "fire",
    icon: HiFire,
    color: "red",
    isActive: true,
  },
  {
    name: "water",
    icon: GiWaterDrop,
    color: "blue",
    isActive: true,
  },
  {
    name: "air",
    icon: WiWindy,
    color: "white",
    isActive: true,
  },
  {
    name: "earth",
    icon: GiGroundSprout,
    color: "brown",
    isActive: true,
  },
  {
    name: "steam",
    icon: GiSteam,
    color: "white",
    mix: "firewater",
    isActive: false,
  },
  {
    name: "ice",
    icon: GiIceCube,
    color: "blue",
    mix: "airwater",
    isActive: false,
  },
  {
    name: "mountain",
    icon: FaMountain,
    color: "blue-gray",
    mix: "earthearth",
    isActive: false,
  },
  {
    name: "rain",
    icon: GiHeavyRain,
    color: "raining",
    mix: "waterwater",
    isActive: false,
  },
  {
    name: "snow",
    icon: GiSnowing,
    color: "white",
    mix: "icerain",
    isActive: false,
  },
  {
    name: "wind",
    icon: BsWind,
    color: "windy",
    mix: "airair",
    isActive: false,
  },
  {
    name: "tornado",
    icon: GiTornado,
    color: "white",
    mix: "windwind",
    isActive: false,
  },
  {
    name: "campfire",
    icon: GiCampfire,
    color: "burning",
    mix: "firefire",
    isActive: false,
  },
  {
    name: "sun",
    icon: GiStripedSun,
    color: "sunny",
    mix: "firecampfire",
    isActive: false,
  },
  {
    name: "storm",
    icon: IoThunderstormSharp,
    color: "electric",
    mix: "rainrain",
    isActive: false,
  },
  {
    name: "tree",
    icon: FaTree,
    color: "trees",
    mix: "earthrain",
    isActive: false,
  },
  {
    name: "iron",
    icon: GiMetalBar,
    color: "white",
    mix: "earthcampfire",
    isActive: false,
  },
  {
    name: "hatchet",
    icon: GiHatchet,
    color: "white",
    mix: "ironstick",
    isActive: false,
  },
  {
    name: "stick",
    icon: GiWoodStick,
    color: "white",
    mix: "treeearth",
    isActive: false,
  },
  {
    name: "kite",
    icon: GiKite,
    color: "white",
    mix: "stickpaper",
    isActive: false,
  },
  {
    name: "woodpile",
    icon: GiWoodPile,
    color: "white",
    mix: "hatchettree",
    isActive: false,
  },
  {
    name: "saw",
    icon: GiCrosscutSaw,
    color: "white",
    mix: "hatchethatchet",
    isActive: false,
  },
  {
    name: "plank",
    icon: GiWoodBeam,
    color: "white",
    mix: "sawwoodpile",
    isActive: false,
  },
  {
    name: "paper",
    icon: BsFileText,
    color: "white",
    mix: "sawplank",
    isActive: false,
  },
  {
    name: "book",
    icon: GiSpellBook,
    color: "white",
    mix: "paperpaper",
    isActive: false,
  },
  {
    name: "cave",
    icon: GiMountainCave,
    color: "white",
    mix: "mountainmountain",
    isActive: false,
  },
  {
    name: "cabin",
    icon: GiWoodCabin,
    color: "white",
    mix: "cavewoodpile",
    isActive: false,
  },
  {
    name: "house",
    icon: GiFamilyHouse,
    color: "white",
    mix: "cabinplank",
    isActive: false,
  },
  {
    name: "tools",
    icon: BsTools,
    color: "white",
    mix: "bookhatchet",
    isActive: false,
  },
  {
    name: "glass",
    icon: GiGlassShot,
    color: "blue",
    mix: "fireearth",
    isActive: false,
  },
  {
    name: "magnify",
    icon: GiMagnifyingGlass,
    color: "glass",
    mix: "glassstick",
    isActive: false,
  },
  {
    name: "microscope",
    icon: GiMicroscope,
    color: "glass",
    mix: "magnifytools",
    isActive: false,
  },
  {
    name: "school",
    icon: FaSchool,
    color: "white",
    mix: "bookhouse",
    isActive: false,
  },
  {
    name: "crop",
    icon: GiWheat,
    color: "white",
    mix: "waterearth",
    isActive: false,
  },
  {
    name: "cloth",
    icon: GiClothes,
    color: "white",
    mix: "cropcrop",
    isActive: false,
  },
  {
    name: "beam",
    icon: GiIBeam,
    color: "white",
    mix: "ironcampfire",
    isActive: false,
  },
  {
    name: "building",
    icon: BsBuilding,
    color: "white",
    mix: "beamhouse",
    isActive: false,
  },
  {
    name: "factory",
    icon: GiFactory,
    color: "white",
    mix: "buildinggenerator",
    isActive: false,
  },
  {
    name: "generator",
    icon: GiLightningArc,
    color: "electric",
    mix: "electricityscience",
    isActive: false,
  },
  {
    name: "science",
    icon: GiChemicalDrop,
    color: "white",
    mix: "microscopewater",
    isActive: false,
  },
  {
    name: "pills",
    icon: GiMedicines,
    color: "white",
    mix: "sciencebacteria",
    isActive: false,
  },
  {
    name: "bacteria",
    icon: FaBacteria,
    color: "white",
    mix: "sciencewater",
    isActive: false,
  },
  {
    name: "electricity",
    icon: GiPlug,
    color: "electric",
    mix: "lightningscience",
    isActive: false,
  },
  {
    name: "lightning",
    icon: GiLightBulb,
    color: "electric",
    mix: "kitestorm",
    isActive: false,
  },
  {
    name: "train",
    icon: GiSteamLocomotive,
    color: "white",
    mix: "steamfactory",
    isActive: false,
  },
  {
    name: "caveman",
    icon: GiCaveman,
    color: "white",
    mix: "cavefire",
    isActive: false,
  },
  {
    name: "farmer",
    icon: GiFarmer,
    color: "white",
    mix: "cavemancrop",
    isActive: false,
  },
  {
    name: "family",
    icon: MdOutlineFamilyRestroom,
    color: "white",
    mix: "farmerfarmer",
    isActive: false,
  },
  {
    name: "wheel",
    icon: GiCartwheel,
    color: "white",
    mix: "cavemantools",
    isActive: false,
  },
  {
    name: "automobile",
    icon: GiRaceCar,
    color: "white",
    mix: "wheelscience",
    isActive: false,
  },
  {
    name: "explosive",
    icon: GiMineExplosion,
    color: "white",
    mix: "sciencefire",
    isActive: false,
  },
  {
    name: "college",
    icon: FcLibrary,
    color: "white",
    mix: "scienceschool",
    isActive: false,
  },
  {
    name: "scientist",
    icon: GiMadScientist,
    color: "white",
    mix: "collegefarmer",
    isActive: false,
  },
  {
    name: "atom",
    icon: GiMaterialsScience,
    color: "white",
    mix: "scientistscience",
    isActive: false,
  },
  {
    name: "fatguy",
    icon: GiMushroomCloud,
    color: "white",
    mix: "atomexplosive",
    isActive: false,
  },
  {
    name: "death",
    icon: GiAngelOutfit,
    color: "white",
    mix: "fatguyfamily",
    isActive: false,
  },
];
