import {
  GiCampfire,
  GiGroundSprout,
  GiStripedSun,
  GiSteam,
  GiWaterDrop,
  GiIceCube,
  GiHeavyRain,
  GiTornado,
  GiSnowing,
} from "react-icons/gi";
import { IoThunderstormSharp } from "react-icons/io5";
import { HiFire } from "react-icons/hi";
import { WiWindy } from "react-icons/wi";
import { BsWind, BsBraces } from "react-icons/bs";
import { FaMountain, FaTree } from "react-icons/fa";
import { IconType } from "react-icons";

export interface ingredient {
  name: string;
  isActive: boolean;
  icon?: IconType;
  color: string;
  mix?: string;
}

export const ingredientsArr: ingredient[] = [
  {
    name: "fire",
    icon: HiFire,
    color: "red",
    isActive: true,
  },
  {
    name: "water",
    icon: GiWaterDrop,
    color: "blue",
    isActive: true,
  },
  {
    name: "air",
    icon: WiWindy,
    color: "white",
    isActive: true,
  },
  {
    name: "earth",
    icon: GiGroundSprout,
    color: "brown",
    isActive: true,
  },
  {
    name: "steam",
    icon: GiSteam,
    color: "white",
    mix: "firewater",
    isActive: false,
  },
  {
    name: "ice",
    icon: GiIceCube,
    color: "blue",
    mix: "airwater",
    isActive: false,
  },
  {
    name: "mountain",
    icon: FaMountain,
    color: "blue-gray",
    mix: "earthearth",
    isActive: false,
  },
  {
    name: "rain",
    icon: GiHeavyRain,
    color: "raining",
    mix: "waterwater",
    isActive: false,
  },
  {
    name: "snow",
    icon: GiSnowing,
    color: "white",
    mix: "icerain",
    isActive: false,
  },
  {
    name: "wind",
    icon: BsWind,
    color: "windy",
    mix: "airair",
    isActive: false,
  },
  {
    name: "tornado",
    icon: GiTornado,
    color: "white",
    mix: "windwind",
    isActive: false,
  },
  {
    name: "campfire",
    icon: GiCampfire,
    color: "burning",
    mix: "firefire",
    isActive: false,
  },
  {
    name: "sun",
    icon: GiStripedSun,
    color: "sunny",
    mix: "firecampfire",
    isActive: false,
  },
  {
    name: "storm",
    icon: IoThunderstormSharp,
    color: "electric",
    mix: "rainrain",
    isActive: false,
  },
  {
    name: "tree",
    icon: FaTree,
    color: "trees",
    mix: "earthrain",
    isActive: false,
  },
  {
    name: "iron",
    icon: BsBraces,
    color: "white",
    mix: "earthcampfire",
    isActive: false,
  },
  {
    name: "hatchet",
    icon: BsBraces,
    color: "white",
    mix: "ironstick",
    isActive: false,
  },
  {
    name: "stick",
    icon: BsBraces,
    color: "white",
    mix: "treeearth",
    isActive: false,
  },
  {
    name: "kite",
    icon: BsBraces,
    color: "white",
    mix: "stickpaper",
    isActive: false,
  },
  {
    name: "woodpile",
    icon: BsBraces,
    color: "white",
    mix: "hatchettree",
    isActive: false,
  },
  {
    name: "saw",
    icon: BsBraces,
    color: "white",
    mix: "hatchethatchet",
    isActive: false,
  },
  {
    name: "plank",
    icon: BsBraces,
    color: "white",
    mix: "sawwoodpile",
    isActive: false,
  },
  {
    name: "paper",
    icon: BsBraces,
    color: "white",
    mix: "sawplank",
    isActive: false,
  },
  {
    name: "book",
    icon: BsBraces,
    color: "white",
    mix: "paperpaper",
    isActive: false,
  },
  {
    name: "cave",
    icon: BsBraces,
    color: "white",
    mix: "mountainmountain",
    isActive: false,
  },
  {
    name: "cabin",
    icon: BsBraces,
    color: "white",
    mix: "cavewoodpile",
    isActive: false,
  },
  {
    name: "house",
    icon: BsBraces,
    color: "white",
    mix: "cabinplank",
    isActive: false,
  },
  {
    name: "tools",
    icon: BsBraces,
    color: "white",
    mix: "bookhatchet",
    isActive: false,
  },
  {
    name: "glass",
    icon: BsBraces,
    color: "white",
    mix: "fireearth",
    isActive: false,
  },
  {
    name: "magnify",
    icon: BsBraces,
    color: "white",
    mix: "glassstick",
    isActive: false,
  },
  {
    name: "microscope",
    icon: BsBraces,
    color: "white",
    mix: "magnifytools",
    isActive: false,
  },
  {
    name: "school",
    icon: BsBraces,
    color: "white",
    mix: "bookhouse",
    isActive: false,
  },
  {
    name: "crop",
    icon: BsBraces,
    color: "white",
    mix: "waterearth",
    isActive: false,
  },
  {
    name: "cloth",
    icon: BsBraces,
    color: "white",
    mix: "cropcrop",
    isActive: false,
  },
  {
    name: "beam",
    icon: BsBraces,
    color: "white",
    mix: "ironcampfire",
    isActive: false,
  },
  {
    name: "building",
    icon: BsBraces,
    color: "white",
    mix: "beamhouse",
    isActive: false,
  },
  {
    name: "factory",
    icon: BsBraces,
    color: "white",
    mix: "buildinggenerator",
    isActive: false,
  },
  {
    name: "generator",
    icon: BsBraces,
    color: "white",
    mix: "electricityscience",
    isActive: false,
  },
  {
    name: "science",
    icon: BsBraces,
    color: "white",
    mix: "microscopewater",
    isActive: false,
  },
];
